name: Build and Publish Tang Container

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Containerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test container
      run: |
        # Pull the built image for testing (try different tag variations)
        docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest || \
        docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} || \
        echo "Using locally built image"
        
        # Create a named volume for testing (eliminates permission issues)
        docker volume create tang-test-keys
        
        # Run container in test mode with named volume
        docker run --rm -d \
          --name tang-test \
          -p 7500:80 \
          -v tang-test-keys:/var/db/tang \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest || \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} || \
          tang-server:latest
        
        # Wait for container to start and generate keys
        sleep 15
        
        # Check if container is running
        docker ps | grep tang-test
        
        # Check container logs for any errors
        echo "=== Container Logs ==="
        docker logs tang-test
        
        # Test if Tang server responds with valid JSON
        echo "=== Testing Tang Server Response ==="
        RESPONSE=$(curl -s http://localhost:7500/adv || echo '{"error": "no response"}')
        echo "Response: $RESPONSE"
        
        # Validate the response is proper JSON and contains expected fields
        echo "$RESPONSE" | python3 -c "
        import sys, json
        try:
            data = json.load(sys.stdin)
            if 'payload' in data:
                print('✅ Tang server responding with valid advertisement')
                sys.exit(0)
            else:
                print('❌ Response missing payload field')
                sys.exit(1)
        except json.JSONDecodeError:
            print('❌ Response is not valid JSON')
            sys.exit(1)
        "
        
        # Check if keys were generated inside the container
        echo "=== Checking Key Generation ==="
        docker exec tang-test ls -la /var/db/tang/ || echo "Could not list keys directory"
        
        # Verify key count
        KEY_COUNT=$(docker exec tang-test sh -c 'ls /var/db/tang/*.jwk 2>/dev/null | wc -l' || echo "0")
        echo "Generated $KEY_COUNT key files"
        
        if [ "$KEY_COUNT" -gt 0 ]; then
          echo "✅ Keys generated successfully"
        else
          echo "❌ No keys found"
        fi
        
        # Clean up
        docker stop tang-test || true
        docker volume rm tang-test-keys || true

  security-scan:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: read
      security-events: write

    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
